version: '3'
services:
  appliance:
    image: "appliance:latest"
    ports:
      - "127.0.0.1:9000:8080"
  doorbell:
    image: "doorbell:latest"
    ports:
      - "127.0.0.1:9001:8080"
  light:
    image: "light:latest"
    ports:
      - "127.0.0.1:9002:8080"
  thermostat:
    image: "thermostat:latest"
    ports:
      - "127.0.0.1:9003:8080"
  home:
    image: "home:latest"
    ports:
      - "127.0.0.1:9004:8080"
  elucidation:
    image: "fortitudetec/elucidation-server"
    ports:
      - "127.0.0.1:9100:8080"
